-- =============================================================
-- 词灵学园 种子数据
-- =============================================================
USE `word_spirit`;

-- 商城商品（金币商城：勋章 / 称号 / 备考资料）
INSERT INTO `shop_item` (`name`, `category`, `icon`, `price`, `description`, `resource_key`) VALUES
('萌芽勋章',   'medal',     'sprout', 500,  '每天一点点，让成长悄悄生根', NULL),
('破茧勋章',   'medal',     'feather', 3000, '熬过无人问津的日子，终会破茧成蝶', NULL),
('登峰勋章',   'medal',     'mountain', 8000, '一步一个脚印，山顶的风景值得你坚持', NULL),
('传奇勋章',   'medal',     'crown', 15000, '以词为剑，以恒为盾，做学习的传奇', NULL),
('称号·学无止境',  'title',     'graduation-cap', 1200, '学海无涯的成长标志', NULL),
('称号·记忆大师',  'title',     'lightbulb', 4000, '你的记忆力非同凡响', NULL),
('称号·一词封神',  'title',     'trophy', 12000, '掌握破万词汇的封神荣耀', NULL),
('中考核心词汇速记', 'resource', '📙', 250, '中考词频 TOP300 · 音标+释义速记', 'zk_words'),
('四级高频词速记手册', 'resource', '📘', 300, 'CET-4 大纲核心词 3849 · 附音标释义', 'cet4_words'),
('六级高频词速记手册', 'resource', '📗', 350, 'CET-6 大纲核心词 5407 · 附音标释义', 'cet6_words'),
('六级翻译高频词·句型模板', 'resource', 'languages', 380, '中国文化高频词 + 翻译句型 20 式', 'cet6_translation'),
('四六级高频短语速查', 'resource', '🔖', 400, '130+ 必背短语 · 阅读写作双高频', 'phrases'),
('四六级写作万能句型', 'resource', '✍️', 450, '60+ 高分句型 · 开头论证结尾全覆盖', 'writing'),
('高考高频词+满分作文模板', 'resource', '📚', 500, 'TOP500 高频词 + 读后续写/应用文模板', 'gk_pack'),
('考研英语核心高频词汇', 'resource', '📕', 600, '大纲词频 TOP800 · 按真题词频排序', 'kaoyan_words');

-- 词典种子单词（基础释义完全本地，不消耗AI额度）
INSERT INTO `dict_word` (`word`, `phonetic`, `pos`, `meaning`, `example`, `example_cn`, `difficulty`) VALUES
('abandon',    '/əˈbændən/',   'v.', '放弃；抛弃',           'Never abandon your dream.', '永远不要放弃你的梦想。', 3),
('ability',    '/əˈbɪləti/',   'n.', '能力；才能',           'She has the ability to lead.', '她具备领导才能。', 2),
('absorb',     '/əbˈzɔːrb/',   'v.', '吸收；使专注',         'Plants absorb water from soil.', '植物从土壤中吸收水分。', 3),
('academic',   '/ˌækəˈdemɪk/','adj.', '学术的',              'His academic performance is excellent.', '他的学业成绩非常优秀。', 3),
('accept',     '/əkˈsept/',    'v.', '接受；承认',           'Please accept my apology.', '请接受我的道歉。', 2),
('achieve',    '/əˈtʃiːv/',   'v.', '实现；达到',           'You can achieve anything if you try.', '只要努力，你就能实现任何目标。', 2),
('active',     '/ˈæktɪv/',    'adj.', '积极的；活跃的',     'He is active in class.', '他在课堂上很活跃。', 1),
('adapt',      '/əˈdæpt/',    'v.', '适应；改编',           'Animals adapt to their environment.', '动物适应它们的环境。', 3),
('admire',     '/ədˈmaɪər/',  'v.', '钦佩；欣赏',           'I admire her courage.', '我钦佩她的勇气。', 2),
('advantage',  '/ədˈvæntɪdʒ/','n.', '优势；有利条件',       'Speaking English is a big advantage.', '会说英语是一个很大的优势。', 2),
('advice',     '/ədˈvaɪs/',   'n.', '建议',                  'Can you give me some advice?', '你能给我一些建议吗？', 1),
('affect',     '/əˈfekt/',    'v.', '影响',                  'Weather affects my mood.', '天气影响我的心情。', 2),
('agree',      '/əˈɡriː/',   'v.', '同意',                  'I agree with your opinion.', '我同意你的观点。', 1),
('ambition',   '/æmˈbɪʃn/',  'n.', '雄心；抱负',           'His ambition is to become a scientist.', '他的抱负是成为一名科学家。', 3),
('ancient',    '/ˈeɪnʃənt/', 'adj.', '古代的；古老的',      'This is an ancient city.', '这是一座古城。', 2),
('anxious',    '/ˈæŋkʃəs/',  'adj.', '焦虑的；渴望的',      'She is anxious about the exam.', '她为考试感到焦虑。', 2),
('apparent',   '/əˈpærənt/', 'adj.', '明显的；表面上的',    'The reason was apparent.', '原因很明显。', 3),
('appreciate', '/əˈpriːʃieɪt/','v.', '感激；欣赏',          'I really appreciate your help.', '我非常感激你的帮助。', 3),
('approach',   '/əˈproʊtʃ/', 'v./n.', '接近；方法',         'We need a new approach.', '我们需要一种新方法。', 3),
('appropriate','/əˈproʊpriət/','adj.', '适当的',            'Choose appropriate words.', '选择恰当的词语。', 3),
('argue',      '/ˈɑːrɡjuː/', 'v.', '争论；主张',           'They often argue about money.', '他们经常为钱争吵。', 2),
('arrange',    '/əˈreɪndʒ/', 'v.', '安排；整理',           'I will arrange a meeting.', '我会安排一次会议。', 2),
('assess',     '/əˈses/',    'v.', '评估',                  'The teacher will assess our work.', '老师会评估我们的作业。', 3),
('assume',     '/əˈsuːm/',   'v.', '假设；承担',           'Let us assume it is true.', '让我们假设这是真的。', 3),
('attitude',   '/ˈætɪtuːd/', 'n.', '态度',                  'A positive attitude matters.', '积极的态度很重要。', 2),
('benefit',    '/ˈbenɪfɪt/', 'n./v.', '利益；受益',        'Exercise benefits your health.', '锻炼有益健康。', 2),
('beyond',     '/bɪˈjɑːnd/', 'prep.', '超出；在……那边',   'The village is beyond the hill.', '村庄在山的那边。', 2),
('brief',      '/briːf/',    'adj.', '简短的',              'Please give a brief answer.', '请给一个简短的回答。', 1),
('brilliant',  '/ˈbrɪliənt/','adj.', '杰出的；明亮的',      'What a brilliant idea!', '多棒的主意啊！', 3),
('campus',     '/ˈkæmpəs/',  'n.', '校园',                  'The campus is beautiful in spring.', '春天的校园很美。', 2),
('capacity',   '/kəˈpæsəti/', 'n.', '容量；能力',          'The hall has a large capacity.', '这个大厅容量很大。', 3),
('capture',    '/ˈkæptʃər/', 'v.', '捕获；吸引',           'The photo captured the moment.', '这张照片捕捉到了那一刻。', 3),
('career',     '/kəˈrɪr/',   'n.', '职业；生涯',           'She has a brilliant career.', '她有一个辉煌的职业生涯。', 2),
('challenge',  '/ˈtʃælɪndʒ/','n./v.', '挑战',              'Learning English is a challenge.', '学英语是一项挑战。', 2),
('character',  '/ˈkærəktər/','n.', '性格；角色；汉字',     'He has a strong character.', '他性格坚强。', 2),
('cooperate',  '/koʊˈɑːpəreɪt/','v.', '合作',              'We should cooperate with each other.', '我们应该互相合作。', 3),
('curious',    '/ˈkjʊriəs/', 'adj.', '好奇的',              'Kids are curious about everything.', '孩子们对一切都感到好奇。', 2),
('dedicate',   '/ˈdedɪkeɪt/','v.', '奉献；致力于',         'He dedicated himself to science.', '他致力于科学。', 3),
('determine',  '/dɪˈtɜːrmɪn/','v.', '决定；下定决心',      'She determined to succeed.', '她下定决心要成功。', 3),
('efficient',  '/ɪˈfɪʃnt/',  'adj.', '高效的',              'This method is more efficient.', '这个方法更高效。', 3),
('effort',     '/ˈefərt/',   'n.', '努力',                  'Success needs great effort.', '成功需要很大的努力。', 1),
('emotion',    '/ɪˈmoʊʃn/',  'n.', '情感；情绪',           'Music can express emotion.', '音乐可以表达情感。', 2),
('enthusiasm', '/ɪnˈθuːziæzəm/','n.', '热情',              'She showed great enthusiasm.', '她表现出极大的热情。', 3),
('essential',  '/ɪˈsenʃl/',  'adj.', '必要的；本质的',     'Water is essential for life.', '水是生命所必需的。', 3),
('flexible',   '/ˈfleksəbl/', 'adj.', '灵活的',            'My schedule is flexible.', '我的时间很灵活。', 3),
('frequent',   '/ˈfriːkwənt/','adj.', '频繁的',            'He is a frequent visitor.', '他是常客。', 2),
('genuine',    '/ˈdʒenjuɪn/', 'adj.', '真正的；真诚的',    'She showed genuine concern.', '她表现出真诚的关心。', 3),
('influence',  '/ˈɪnfluəns/','n./v.', '影响',              'Parents influence their children.', '父母影响孩子。', 2),
('intention',  '/ɪnˈtenʃn/', 'n.', '意图；打算',           'He had no intention to hurt you.', '他没有伤害你的意图。', 3),
('motivate',   '/ˈmoʊtɪveɪt/','v.', '激励',                'Good teachers motivate students.', '好老师会激励学生。', 3),
('opportunity','/ˌɑːpərˈtuːnəti/','n.', '机会',            'Seize every opportunity.', '抓住每一个机会。', 3),
('passion',    '/ˈpæʃn/',    'n.', '激情；热爱',           'She has a passion for music.', '她热爱音乐。', 2),
('persevere',  '/ˌpɜːrsəˈvɪr/','v.', '坚持不懈',           'Persevere and you will win.', '坚持就会胜利。', 4),
('potential',  '/pəˈtenʃl/', 'n./adj.', '潜力；潜在的',    'He has great potential.', '他潜力巨大。', 3),
('precious',   '/ˈpreʃəs/',  'adj.', '珍贵的',              'Time is precious.', '时间很宝贵。', 2),
('priority',   '/praɪˈɔːrəti/','n.', '优先事项',           'Health is a top priority.', '健康是头等大事。', 3),
('prosper',    '/ˈprɑːspər/','v.', '繁荣；成功',           'The town prospered over the years.', '小镇多年来日益繁荣。', 4),
('reliable',   '/rɪˈlaɪəbl/', 'adj.', '可靠的',            'He is a reliable friend.', '他是一个可靠的朋友。', 3),
('struggle',   '/ˈstrʌɡl/',  'v./n.', '奋斗；挣扎',        'We must struggle for our dreams.', '我们必须为梦想而奋斗。', 2),
('sufficient', '/səˈfɪʃnt/', 'adj.', '足够的',              'We have sufficient time.', '我们有足够的时间。', 3),
('tremendous', '/trəˈmendəs/','adj.', '巨大的',            'It was a tremendous success.', '这是一次巨大的成功。', 4),
('vital',      '/ˈvaɪtl/',   'adj.', '至关重要的',         'Sleep is vital to health.', '睡眠对健康至关重要。', 3),
('wisdom',     '/ˈwɪzdəm/',  'n.', '智慧',                  'True wisdom comes from experience.', '真正的智慧来自经验。', 3);

-- =============================================================
-- 每日任务模板库（随机推送，每日不重复；每类多个变体随机抽 1 个）
-- 类别说明：review=复习 / newWord=学新词 / aiUse=词灵AI / game=游戏 / paper=试卷
-- 完成态由对应行为判定，points 与 TASK_POINTS 保持一致
-- =============================================================
INSERT INTO `task_template` (`category`, `title`, `description`, `icon`, `path`, `points`, `weight`, `enabled`) VALUES
('review',  '复习今日到期单词', '艾宾浩斯计划安排的单词，今日记得回顾', 'book-open', '/review', 10, 1, 1),
('review',  '清空今日复习计划', '把待复习清单全部过一遍更扎实', 'book-open', '/review', 10, 1, 1),
('review',  '巩固待复习词', '温故而知新，别让单词溜走', 'book-open', '/review', 10, 1, 1),
('newWord', '学习 5 个新单词', '认识的词会自动加入生词本', 'brain', '/review', 15, 1, 1),
('newWord', '认识 5 个生词', '每天扩充一点词汇量', 'brain', '/review', 15, 1, 1),
('newWord', '积累 5 个新词汇', '积少成多，词汇量悄悄上涨', 'brain', '/review', 15, 1, 1),
('aiUse',   '用一次词灵AI', '阅读解析 / 生词巩固 / 自由答疑任选', 'sparkles', '/ai-assistant', 10, 1, 1),
('aiUse',   '让词灵解析一段阅读', '把难句交给 AI 拆解', 'sparkles', '/ai-assistant', 10, 1, 1),
('aiUse',   '向词灵 AI 提个问题', '有不懂的就问词灵', 'sparkles', '/ai-assistant', 10, 1, 1),
('game',    '玩一局单词游戏', '在游戏中巩固单词还能赚金币', 'gamepad-2', '/game-park', 20, 1, 1),
('game',    '挑战一局拼写游戏', '手脑并用记得更牢', 'gamepad-2', '/game-park', 20, 1, 1),
('game',    '用游戏巩固单词', '寓教于乐，轻松记词', 'gamepad-2', '/game-park', 20, 1, 1),
('paper',   '做一套练习试卷', '检验学习成果，错题自动收录', 'file-text', '/paper-list', 25, 1, 1),
('paper',   '完成一份单元测试', '看看今天学得怎么样', 'file-text', '/paper-list', 25, 1, 1),
('paper',   '做卷子检验成果', '以测促学，查漏补缺', 'file-text', '/paper-list', 25, 1, 1);
