-- =============================================================
-- 中考词库补丁：中考大纲词汇（来源：KyleBing/english-vocabulary「初中」词表，CC BY 4.0）
-- 只补入「中考有、现有四六级/基础/高考词库没有」的差集单词，与已有词库零重复
-- difficulty=1（最易档，低于高考=3、四级=2、六级=4），level='zhongkao'；幂等导入可重复执行
-- 用法：DBeaver 打开本文件（确认编码 UTF-8），不选中任何内容，Alt+X 执行整个脚本
-- =============================================================
USE `word_spirit`;

INSERT IGNORE INTO `dict_word` (`word`,`pos`,`meaning`,`difficulty`,`level`) VALUES
('alright','adv','好， 好吧',1,'zhongkao'),
('anymore','adv','再， 更， 还； 目前， 现在， 今后',1,'zhongkao'),
('autograph','v/n','签名 n. 亲笔签名',1,'zhongkao'),
('brazilian','adj/n','巴西的； 巴西人的 n. 巴西人',1,'zhongkao'),
('casually','adv','偶然地； 随便地； 临时地',1,'zhongkao'),
('chore','n','家庭杂务； 困难的工作； 令人厌烦的工作',1,'zhongkao'),
('cola','n','可乐饮料',1,'zhongkao'),
('con','n','反对票， 反对论',1,'zhongkao'),
('eighteenth','num','第十八',1,'zhongkao'),
('escalator','n','〈美〉自动扶梯',1,'zhongkao'),
('etiquette','n','礼节， 礼仪',1,'zhongkao'),
('favorite','adj/n','特别喜爱的 n. 特别喜欢的人或事物',1,'zhongkao'),
('fifteenth','num/n','第十五 n. 十五分之一',1,'zhongkao'),
('fourteenth','num/n','第十四 n. 十四分之一',1,'zhongkao'),
('furry','adj','毛皮的， 盖着毛皮的',1,'zhongkao'),
('girlfriend','n','女朋友； 女性朋友',1,'zhongkao'),
('grandparent','n','祖父母；祖父或祖母；外祖父母；外祖父或外祖母',1,'zhongkao'),
('hallway','n','走廊， 回廊； 门厅， 过道',1,'zhongkao'),
('homeless','adj','无家的， 无家可归的',1,'zhongkao'),
('impolite','adj','不礼貌的， 粗鲁的',1,'zhongkao'),
('infinitive','n','原形； 不定式',1,'zhongkao'),
('jew','n','犹太人； 犹太教徒',1,'zhongkao'),
('kilometer','n','[计量] 公里；[计量] 千米（等于kilometre）',1,'zhongkao'),
('labor','n','劳动； 工作',1,'zhongkao'),
('lifestyle','n','生活方式',1,'zhongkao'),
('lighting','n','照明； 照明设备； 光线',1,'zhongkao'),
('lookout','n','警戒， 监视； ■望台， 监视哨； ■望员， 监视者； 与个人有关的事情， 任务',1,'zhongkao'),
('loving','adj','爱的； 充满爱的； 钟爱的',1,'zhongkao'),
('math','n','数学（等于mathematics）',1,'zhongkao'),
('misleading','adj','令人误解的， 导致错误结论的； 引入歧途的； 欺骗的； 迷惑人的',1,'zhongkao'),
('neighbor','n','邻居； 邻国',1,'zhongkao'),
('nineteenth','num/n','第十九 n. 十九分之一',1,'zhongkao'),
('online','adj','在线的； 联机的， 联网的',1,'zhongkao'),
('pro','n/adj/prep','〔相对于业余爱好者而言的〕专业人士，职业人员〔尤指职业运动员〕 adj. 职业性的；专业的 prep. 赞成的，支持的',1,'zhongkao'),
('restroom','n','洗手间； 休息室',1,'zhongkao'),
('rusia','','鲁西亚（地名）',1,'zhongkao'),
('scared','adj','惊恐的， 恐惧的',1,'zhongkao'),
('schoolwork','n','学校作业， 课堂作业； 家庭作业',1,'zhongkao'),
('seventeenth','num/n','第十七 n. 十七分之一',1,'zhongkao'),
('shampoo','n/vt','洗发剂；洗涤剂 vt. 用洗发剂洗头',1,'zhongkao'),
('shiny','adj','光亮的， 有光泽的； 反光的',1,'zhongkao'),
('slipper','v/n','用拖鞋打 n. 拖鞋；轻便舞鞋',1,'zhongkao'),
('socks','n','袜子（sock的复数）',1,'zhongkao'),
('southeast','adv/adj/n','向东南 adj. 东南方的， 东南部的， 来自东南的 n. 东南，东南',1,'zhongkao'),
('specially','adv','特意地， 专门地； 格外地， 特别地， 特殊地',1,'zhongkao'),
('spotlight','v/n','用聚光灯照； 特别关注； 突出报道 n. 聚光灯；公众的注意',1,'zhongkao'),
('stairs','n','楼梯；梯级（stair的复数）',1,'zhongkao'),
('star','n','星； 星形； 明星， 名角',1,'zhongkao'),
('summer','n','夏天， 夏季',1,'zhongkao'),
('talented','adj','有才能的， 有才干的； 天才的',1,'zhongkao'),
('teen','adj/n','青少年的 n. 少年男女，青少年',1,'zhongkao'),
('tennis','n','网球',1,'zhongkao'),
('tenth','num/adj','第十；十分之一 adj. 十分之一的；第十个的',1,'zhongkao'),
('theater','n','戏院， 剧场； 影剧院',1,'zhongkao'),
('thirteenth','num/n','第十三 n. 十三分之一',1,'zhongkao'),
('thirtieth','num/n','第三十 n. 三十分之一',1,'zhongkao'),
('underwater','adv/adj','在水下， 在水中 adj. 水下的；水下使用的；水下行动的',1,'zhongkao'),
('unfamiliar','adj','不熟悉的',1,'zhongkao'),
('unfriendly','adj','不友好的， 冷漠的',1,'zhongkao'),
('vcd','abbr','视频高密光盘（Video Compact Disc）；可变电容二极管（Variable Capacitance Diode）',1,'zhongkao'),
('verb','n','动词',1,'zhongkao'),
('yang','n','阳',1,'zhongkao'),
('yeah','adv','是',1,'zhongkao'),
('yin','n','阴',1,'zhongkao'),
('yogurt','n','酸奶， 酵母乳',1,'zhongkao'),
('zigzag','adj/v/n','“之”字形的 v. 弯弯曲曲行进 n. “之”字形；蜿蜒曲折',1,'zhongkao');

-- 校验
-- SELECT level, COUNT(*) FROM dict_word GROUP BY level;
