-- =============================================================
-- 高考词库补丁：高考大纲词汇（来源：KyleBing/english-vocabulary「高中」词表，CC BY 4.0）
-- 只补入「高考有、现有四六级/基础词库没有」的差集单词，与四六级零重复
-- difficulty=3（四级=2、六级=4 之间），level='gaokao'；幂等导入可重复执行
-- 用法：DBeaver 打开本文件（确认编码 UTF-8），不选中任何内容，Alt+X 执行整个脚本
-- =============================================================
USE `word_spirit`;

INSERT IGNORE INTO `dict_word` (`word`,`pos`,`meaning`,`difficulty`,`level`) VALUES
('addicted','adj/v','沉溺于某种（尤其是不良的）嗜好的；入了迷的，上了瘾的 v. 使…上瘾（addict的过去分词）',3,'gaokao'),
('adjustment','n','调整，调节；调节器',3,'gaokao'),
('admirable','adj','令人钦佩的；极好的；值得赞扬的',3,'gaokao'),
('adolescence','n','青春期',3,'gaokao'),
('afterwards','adv','后来',3,'gaokao'),
('aggression','n','侵略；进攻；侵犯；侵害',3,'gaokao'),
('agricultural','adj','农业的；农艺的',3,'gaokao'),
('aids','abbr','获得性免疫缺乏综合征；爱滋病（Acquired Immune Deficiency Syndrome）',3,'gaokao'),
('airmail','n','航空邮件',3,'gaokao'),
('airspace','n','空域；领空；空间',3,'gaokao'),
('alcoholic','adj/n','酒精的，含酒精的 n. 酒鬼，酗酒者',3,'gaokao'),
('alley','n','小巷；小路；小径',3,'gaokao'),
('aluminum','n','铝',3,'gaokao'),
('amazing','adj/v','令人惊异的 v. 使吃惊（amaze的ing形式）',3,'gaokao'),
('ambassadress','n','大使夫人； 女大使',3,'gaokao'),
('anecdote','n','轶事；奇闻；秘史',3,'gaokao'),
('announcement','n','公告；宣告；发表；通告',3,'gaokao'),
('antarctic','adj/n','南极的 n. 南极地区',3,'gaokao'),
('apron','n/vt','围裙；[航] 停机坪；舞台口 vt. 着围裙于；围绕',3,'gaokao'),
('arabic','adj/n','阿拉伯的；阿拉伯人的 n. 阿拉伯语',3,'gaokao'),
('armchair','n/adj','扶手椅，单人沙发 adj. 不切实际的',3,'gaokao'),
('astronomer','n','天文学家',3,'gaokao'),
('attentively','adv','注意地；聚精会神地；周到地',3,'gaokao'),
('backache','n','背痛；腰痛',3,'gaokao'),
('ballpoint','n','圆珠笔',3,'gaokao'),
('barbecue','n/v','烤肉；吃烤肉的野宴 v. 烧烤；烤肉',3,'gaokao'),
('barbershop','n/adj','理发店 adj. 有男声合唱之和声的',3,'gaokao'),
('bathrobe','n','浴衣；睡衣',3,'gaokao'),
('bathtub','n','浴缸',3,'gaokao'),
('battleground','n','战场',3,'gaokao'),
('beancurd','n','豆腐',3,'gaokao'),
('bedclothes','n','床上用品；铺盖',3,'gaokao'),
('beddings','n/adj/vt/vi','寝具；（建筑）[建] 基床；（家畜）草垫 adj. 适于花坛种植的 vt. 把…栽入苗床（bed的ing形式） vi. 睡（bed的ing形式）',3,'gaokao'),
('bedroom','n/adj','卧室 adj. 两性关系的；城郊住宅区的',3,'gaokao'),
('beehive','n','蜂窝；蜂箱',3,'gaokao'),
('behaviour','n','[U] 行为， 举止',3,'gaokao'),
('behavious','n','行为',3,'gaokao'),
('belgium','n','比利时（西欧国家，首都布鲁塞尔Brussels）',3,'gaokao'),
('bent','n/adj','爱好，嗜好 adj. 弯曲的；决心的',3,'gaokao'),
('bingo','n','宾戈游戏',3,'gaokao'),
('birdcage','n','鸟笼；鸟笼状物；信号灯；宿舍',3,'gaokao'),
('birthplace','n','出生地',3,'gaokao'),
('boating','n/adj/v','划船 adj. 划船的 v. 划船（boat的ing形式）',3,'gaokao'),
('bookcase','n','[家具] 书柜，书架',3,'gaokao'),
('bookmark','n','书签（等于bookmarker）；标记',3,'gaokao'),
('bookshelf','n','书架',3,'gaokao'),
('bookshop','n','书店',3,'gaokao'),
('bookstore','n','书店（等于bookshop）',3,'gaokao'),
('bored','adj/v','无聊的；无趣的；烦人的 v. 使厌烦（bore的过去式）；烦扰',3,'gaokao'),
('botany','n','植物学；地区植物总称',3,'gaokao'),
('bowling','n/v','滚木球戏；保龄球戏 v. 打保龄球（bowl的现在分词）',3,'gaokao'),
('boxing','n/v','拳击；装箱；围模；做箱的材料 v. 将…装入盒中（box的ing形式）',3,'gaokao'),
('bravery','n','勇敢；勇气',3,'gaokao'),
('breathless','adj','喘不过气来的；停止呼吸的',3,'gaokao'),
('brewery','n','啤酒厂',3,'gaokao'),
('brotherhood','n','兄弟关系；手足情谊；四海之内皆兄弟的信念',3,'gaokao'),
('brunch','n','早午餐',3,'gaokao'),
('buddhist','n/adj','佛教徒 adj. 佛教的',3,'gaokao'),
('buffet','n/v/adj','自助餐；小卖部；打击；猛烈冲击 v. 与…搏斗；连续猛击 adj. 自助的；自助餐的',3,'gaokao'),
('bun','n','小圆面包',3,'gaokao'),
('bungalow','n','平房；小屋',3,'gaokao'),
('bureaucratic','adj','官僚的；官僚政治的',3,'gaokao'),
('businessman','n','商人',3,'gaokao'),
('businesswoman','n','女商人',3,'gaokao'),
('bye','n/adj','再见 n. 轮空；次要的东西 adj. 次要的',3,'gaokao'),
('cab','n/v','驾驶室；出租汽车；出租马车 v. 乘出租马车（或汽车）',3,'gaokao'),
('cd','abbr','光盘，激光唱片（Compact Disc）；呼叫设备（Calling Device）；中央地区（Central District）；商务部（Commerce Department）',3,'gaokao'),
('celebration','n','庆典，庆祝会；庆祝；颂扬',3,'gaokao'),
('chairwoman','n','女主席；女议长',3,'gaokao'),
('challenging','adj/v','挑战的；引起挑战性兴趣的 v. 要求；质疑；反对；向…挑战；盘问（challenge的ing形式）',3,'gaokao'),
('changeable','adj','无常的；可改变的；易变的；不定的',3,'gaokao'),
('cheers','v','感谢；谢谢；再见',3,'gaokao'),
('chick','n/adj','小鸡；小鸟；少妇 adj. 胆小的；懦弱的',3,'gaokao'),
('chips','n','[食品] 炸土豆条；小木片；（作赌注用的）圆形筹码；缺口（chip的复数形式）',3,'gaokao'),
('choir','n/v','唱诗班；合唱队；舞蹈队 v. 合唱',3,'gaokao'),
('chopsticks','n','筷子',3,'gaokao'),
('cleaner','n','[化工] 清洁剂；清洁工；干洗店；干洗商；洗洁器',3,'gaokao'),
('cocoa','n','可可粉；可可豆；可可饮料；深褐色',3,'gaokao'),
('colour','v/n','把…涂颜色，粉饰；歪曲；使脸红 n. 颜色；风格；气色，面色；外貌',3,'gaokao'),
('comma','n','逗号；停顿',3,'gaokao'),
('contradictory','adj/n','矛盾的；反对的；反驳的；抗辩的 n. 对立物；矛盾因素',3,'gaokao'),
('cooker','n','炊具；烹饪用水果；窜改者',3,'gaokao'),
('cookie','n','饼干；小甜点',3,'gaokao'),
('coral','n/adj','珊瑚；珊瑚虫 adj. 珊瑚的；珊瑚色的',3,'gaokao'),
('cordless','n/adj','不用电线的 adj. 无线的（副词cordlessly）',3,'gaokao'),
('cosy','adj/n','舒适的；惬意的 n. 保温罩',3,'gaokao'),
('cowboy','n','牛仔；牧童；莽撞的人',3,'gaokao'),
('crayon','n/v','蜡笔，有色粉笔 v. 以蜡笔作画，用颜色粉笔画',3,'gaokao'),
('crossroads','n','十字路口；交叉路口；聚会的中心地点（crossroad的复数形式）',3,'gaokao'),
('crowded','adj/v','拥挤的；塞满的 v. 拥挤（crowd的过去分词）',3,'gaokao'),
('cuisine','n','烹饪，烹调法',3,'gaokao'),
('customs','n','海关；风俗（custom的复数）；习惯；关税',3,'gaokao'),
('cyclist','n','骑自行车的人',3,'gaokao'),
('dad','n','爸爸；爹爹',3,'gaokao'),
('darkness','n','黑暗；模糊；无知；阴郁',3,'gaokao'),
('decoration','n','装饰，装潢；装饰品；奖章',3,'gaokao'),
('deeply','adv','深刻地；浓浓地；在深处',3,'gaokao'),
('defense','n/vt','防卫，防护；防御措施；防守 vt. 谋划抵御',3,'gaokao'),
('delighted','adj/v','高兴的；欣喜的 v. 使…兴高采烈；感到快乐（delight的过去分词）',3,'gaokao'),
('dialogue','n/vi/vt','对话；意见交换 vi. 对话 vt. 用对话表达',3,'gaokao'),
('dinosaur','n','恐龙；过时、落伍的人或事物',3,'gaokao'),
('disability','n','残疾；无能；无资格；不利条件',3,'gaokao'),
('disabled','adj/v','残废的，有缺陷的 v. 使…失去能力（disable的过去分词）',3,'gaokao'),
('disappointed','adj','失望的',3,'gaokao'),
('disappointment','n','失望；沮丧',3,'gaokao'),
('disgusting','adj','令人厌恶的',3,'gaokao'),
('disobey','v','违反；不服从',3,'gaokao'),
('disturbing','adj/v','令人不安的；烦扰的 v. 干扰；打断（disturb的ing形式）',3,'gaokao'),
('doll','n/v','洋娃娃；玩偶；无头脑的美丽女人 v. 把…打扮得花枝招展',3,'gaokao'),
('downtown','adv/adj/n','往闹市区；在市区 adj. 市中心的 n. 市中心区；三分线以外',3,'gaokao'),
('dr','abbr','速度三角形定位法（dead reckoning）；数据记录器（Data Recorder）',3,'gaokao'),
('drier','n','干燥机；干燥剂；吹风机',3,'gaokao'),
('dumpling','n','饺子，汤团；面团布丁',3,'gaokao'),
('dustbin','n','垃圾箱；吃货',3,'gaokao'),
('dusty','adj','落满灰尘的',3,'gaokao'),
('dvd','abbr','数字化视频光盘（Digital Video Disk）',3,'gaokao'),
('dynasty','n','王朝，朝代',3,'gaokao'),
('e-mail','n/vt','电子邮件 vt. 给…发电子邮件',3,'gaokao'),
('eastwards','adv/adj','向东方地 adj. 向东方的',3,'gaokao'),
('educator','n','教育家；教育工作者；教师',3,'gaokao'),
('eggplant','n/adj','茄子 adj. 深紫色的',3,'gaokao'),
('egypt','n','埃及（非洲国家）',3,'gaokao'),
('encouragement','n','鼓励',3,'gaokao'),
('enjoyable','adj','快乐的；有乐趣的；令人愉快的',3,'gaokao'),
('eraser','n','橡皮；擦除器；[计] 清除器',3,'gaokao'),
('explorer','n','探险家；勘探者；探测器；[医]探针',3,'gaokao'),
('facial','adj/n','面部的，表面的；脸的，面部用的 n. 美容，美颜；脸部按摩',3,'gaokao'),
('fairness','n','公平；美好；清晰；顺利性',3,'gaokao'),
('fat','adj/n/v','肥的，胖的；油腻的；丰满的 n. 脂肪，肥肉 v. 养肥；在…中加入脂肪',3,'gaokao'),
('fax','v/n','传真 n. 传真',3,'gaokao'),
('fingernail','n','手指甲',3,'gaokao'),
('firefighter','n','消防队员',3,'gaokao'),
('firewood','n','柴火；木柴',3,'gaokao'),
('fireworks','n','烟火',3,'gaokao'),
('firmly','adv','坚定地，坚决地；坚固地，稳固地',3,'gaokao'),
('flaming','adj/v/n','燃烧的；火红的；激昂的 v. 燃烧；变亮；发光（flame的ing形式） n. (Flaming)人名；(法)弗拉曼',3,'gaokao'),
('flashlight','n','手电筒；闪光灯',3,'gaokao'),
('fluency','n','（语言、文章）流利；（技能）娴熟',3,'gaokao'),
('foggy','adj','有雾的；模糊的，朦胧的',3,'gaokao'),
('forgetful','adj','健忘的；不注意的；疏忽的；使遗忘的',3,'gaokao'),
('founding','adj/v/n','创办的；发起的 v. [机] 铸造；建造；以…为基础（found的ing形式） n. [机] 铸造；溶解',3,'gaokao'),
('freeway','n','高速公路',3,'gaokao'),
('freezing','adj','冰冻的；严寒的；冷冻用的',3,'gaokao'),
('frenchman','n','法国人',3,'gaokao'),
('fried','adj/v','油炸的，油煎的；喝醉了的 v. 油炸（fry的过去分词）',3,'gaokao'),
('furnished','adj/v','家具，有家具的 v. 供应；装备（furnish的过去分词）',3,'gaokao'),
('gale','n','[气象] 大风，狂风；（突发的）一阵',3,'gaokao'),
('gardening','n','园艺；园林工人的工作',3,'gaokao'),
('gifted','adj/v','有天赋的；有才华的 v. 给予（gift的过去分词）',3,'gaokao'),
('giraffe','n','长颈鹿',3,'gaokao'),
('glasshouse','n','温室；暖房',3,'gaokao'),
('graduation','n','毕业；毕业典礼；刻度，分度；分等级',3,'gaokao'),
('grandchild','n','孙子；孙女；外孙；外孙女',3,'gaokao'),
('grandma','n','奶奶；外婆',3,'gaokao'),
('grandpa','n','爷爷；外公',3,'gaokao'),
('grandparents','n','祖父母（grandparent的复数）；外祖父母',3,'gaokao'),
('granny','n','奶奶；外婆；婆婆妈妈的人',3,'gaokao'),
('greece','n','希腊（欧洲南部国家）',3,'gaokao'),
('greengrocer','n','蔬菜水果商；菜贩',3,'gaokao'),
('grill','v/n','烧，烤； n. 烤架，铁格子；烤肉',3,'gaokao'),
('gruel','vt/n','使极度疲劳；累垮 n. 稀粥',3,'gaokao'),
('gy','abbr/n','灰色（gray）；圭亚那（Guyana） n. 戈瑞',3,'gaokao'),
('gymnastics','n','体操；体育；体操运动',3,'gaokao'),
('ha','abbr/n','哈！（表示惊异，愉快，怀疑，胜利等） abbr. 一种元素(hahnium,原子序105) n. (Ha)人名；(德)哈；(日)巴 (姓)',3,'gaokao'),
('handtruck','','手推车',3,'gaokao'),
('happily','adv','快乐地；幸福地；幸运地；恰当地',3,'gaokao'),
('hard-working','adj','勤劳的， 辛勤工作的',3,'gaokao'),
('harmless','adj','无害的；无恶意的',3,'gaokao'),
('headmistress','n','女校长',3,'gaokao'),
('headteacher','n','中小学的校长',3,'gaokao'),
('hey','n','喂！（引起注意等）；你好！（表示问候） n. 干草（等于hay）',3,'gaokao'),
('hibernate','v','过冬；（动物）冬眠；（人等）避寒',3,'gaokao'),
('hibernation','n','冬眠；过冬；避寒',3,'gaokao'),
('hilly','adj/n','丘陵的；陡的；多小山的；多坡的 n. (Hilly)人名；(阿拉伯)希利',3,'gaokao'),
('hive','v/n','群居；入蜂房；生活在蜂房中 n. 蜂房，蜂巢；热闹的场所；熙攘喧闹的人群',3,'gaokao'),
('homeland','n','祖国；故乡',3,'gaokao'),
('hometown','n','家乡；故乡',3,'gaokao'),
('homework','n','家庭作业，课外作业',3,'gaokao'),
('hooray','vi/vt/n','呼万岁 vt. 呼万岁 n. 万岁 int. 万岁',3,'gaokao'),
('housework','n','家务事',3,'gaokao'),
('hunter','n','猎人；猎犬；搜寻者',3,'gaokao'),
('hur','abbr','飓风（hurricane）',3,'gaokao'),
('iceland','n','冰岛（欧洲岛名，在大西洋北部，近北极圈）',3,'gaokao'),
('internet','n','因特网',3,'gaokao'),
('ireland','n','爱尔兰',3,'gaokao'),
('irish','adj/n','爱尔兰的；爱尔兰人的 n. 爱尔兰人；爱尔兰语；爱尔兰',3,'gaokao'),
('irrigate','v','灌溉；冲洗；使清新',3,'gaokao'),
('italy','n','意大利（欧洲南部国家）',3,'gaokao'),
('jeep','n','吉普车',3,'gaokao'),
('jewelry','n','珠宝；珠宝类',3,'gaokao'),
('juicy','adj','多汁的；利润多的；生动的',3,'gaokao'),
('kangaroo','n','袋鼠',3,'gaokao'),
('kilo','n','千克',3,'gaokao'),
('labourer','n','劳动者；劳工',3,'gaokao'),
('latest','adv/n/adj','最迟地；最后地 n. 最新的事物 adj. 最新的，最近的；最迟的，最后的',3,'gaokao'),
('leftover','n/adj','残留物；吃剩的饭菜；剩余物 adj. 残余的；吃剩的',3,'gaokao'),
('lemonade','n','柠檬水',3,'gaokao'),
('litre','n','[计量] 公升（米制容量单位）',3,'gaokao'),
('london','n','伦敦',3,'gaokao'),
('lost','adj/v','失去的；丧失的；迷惑的 v. 遗失（lose的过去分词）；失败',3,'gaokao'),
('loudly','adv','大声地，响亮地',3,'gaokao'),
('mailbox','n','邮箱；邮筒',3,'gaokao'),
('marathon','n/adj/vi','马拉松赛跑；耐力的考验 adj. 马拉松式的；有耐力的 vi. 参加马拉松赛跑',3,'gaokao'),
('mentally','adv','精神上，智力上；心理上',3,'gaokao'),
('messy','adj','凌乱的，散乱的；肮脏的，污秽的；麻烦的',3,'gaokao'),
('mexican','adj/n','墨西哥的；墨西哥人的 n. 墨西哥人；墨西哥语',3,'gaokao'),
('mexico','n','墨西哥',3,'gaokao'),
('miniskirt','n','超短裙；迷你短裙',3,'gaokao'),
('mistaken','adj/v','错误的；弄错的；被误解的 v. 弄错（mistake的过去分词）',3,'gaokao'),
('mm','abbr/n','毫米（millimeter） n. 缅甸的域名',3,'gaokao'),
('modem','n','调制解调器（等于modulator-demodulator）',3,'gaokao'),
('mom','n','妈妈',3,'gaokao'),
('mommy','n','妈咪',3,'gaokao'),
('moscow','n','莫斯科（俄罗斯首都）',3,'gaokao'),
('motherland','n','祖国；母国',3,'gaokao'),
('motorbike','n','摩托车',3,'gaokao'),
('motorcycle','n/v','摩托车；机动车 v. 骑摩托车',3,'gaokao'),
('motto','n','座右铭，格言；箴言',3,'gaokao'),
('moustache','n','小胡子；髭；触须',3,'gaokao'),
('nationwide','adj/adv','全国范围的；全国性的 adv. 在全国',3,'gaokao'),
('necktie','n','领带',3,'gaokao'),
('noisily','adv','吵闹地，喧闹地',3,'gaokao'),
('non-stop','adv','adj&adv. 不停的， 不断的',3,'gaokao'),
('noodle','n','面条；笨蛋',3,'gaokao'),
('northwards','adv','向北',3,'gaokao'),
('novelist','n','小说家',3,'gaokao'),
('numb','v/adj','使麻木；使发愣；使失去感觉 adj. 麻木的；发愣的',3,'gaokao'),
('nursing','n/v','护理；看护；养育 v. 看护；养育（nurse的ing形式）',3,'gaokao'),
('offshore','adj/adv','离岸的；[海洋] 近海的；吹向海面的 adv. 向海面，向海',3,'gaokao'),
('oilfield','n','油田',3,'gaokao'),
('ok','adj/adv/v/n','好的；不错的 adv. 行；很好 int. 好；可以 v. 对…表示同意 n. 同意',3,'gaokao'),
('omelette','n','煎蛋卷',3,'gaokao'),
('opener','n','[五金] 开启工具；开启的人',3,'gaokao'),
('organise','v','组织起来；组织工会',3,'gaokao'),
('organiser','n','组织者；发起人；形成体（等于organizer）',3,'gaokao'),
('ottawa','n','渥太华（加拿大首都）',3,'gaokao'),
('ouch','n','扣环 int. 哎哟（突然疼痛时发出的声音）',3,'gaokao'),
('outing','n/adj/v','远足；短途旅游；体育比赛 adj. 远足适用的 v. 出来；暴露（out的ing形式）',3,'gaokao'),
('outspoken','adj','坦率的，直言不讳的',3,'gaokao'),
('paddle','n/v','划桨；明轮翼 v. 拌；搅；用桨划',3,'gaokao'),
('pancake','n/vi/vt','薄烤饼；粉饼；平降（全称pancake landing） vi. 平坠着陆；平展 vt. 使平坠著陆；使平展',3,'gaokao'),
('panda','n','熊猫；猫熊',3,'gaokao'),
('paperwork','n','文书工作',3,'gaokao'),
('paris','n','巴黎（法国首都）；帕里斯（特洛伊王子）',3,'gaokao'),
('parking','n/adj/v','停车 adj. 停车的 v. 停车（park的ing形式）',3,'gaokao'),
('parrot','n/v','鹦鹉；学舌者，应声虫；机械模仿别人的人 v. 机械地模仿',3,'gaokao'),
('passer-by','n','过客， 过路人',3,'gaokao'),
('pavement','n','人行道',3,'gaokao'),
('performer','n','演出者；执行者；演奏者',3,'gaokao'),
('personalization','n','个性化',3,'gaokao'),
('personally','adv','亲自地；当面；个别地；就自己而言',3,'gaokao'),
('pesticide','n','杀虫剂',3,'gaokao'),
('photographer','n','摄影师；照相师',3,'gaokao'),
('pianist','n','钢琴家；钢琴演奏者',3,'gaokao'),
('playmate','n','玩伴；游伴',3,'gaokao'),
('playroom','n','游戏室；娱乐室',3,'gaokao'),
('pleased','adj/v','高兴的；喜欢的；乐意做某事 v. 满意；愿意（please的过去分词形式）',3,'gaokao'),
('pm','abbr','（拉）下午（Post Meridiem，等于afternoon）；调相（Phase Modulation）',3,'gaokao'),
('popcorn','n','爆米花，爆玉米花',3,'gaokao'),
('porridge','n/vt','粥，糊；麦片粥 vt. 服刑',3,'gaokao'),
('postbox','n','邮箱',3,'gaokao'),
('postcard','n','明信片',3,'gaokao'),
('postcode','n','（英）邮政编码；邮区号',3,'gaokao'),
('poster','n','海报，广告；招贴',3,'gaokao'),
('printing','n','印刷；印刷术',3,'gaokao'),
('programme','n/v','计划，规划；节目；程序 v. 编程序；制作节目',3,'gaokao'),
('properly','adv','适当地；正确地；恰当地',3,'gaokao'),
('pub','n','酒馆；客栈',3,'gaokao'),
('publicly','adv','公然地；以公众名义',3,'gaokao'),
('punctuate','v','不时打断；强调；加标点于',3,'gaokao'),
('punctuation','n','标点；标点符号',3,'gaokao'),
('punishment','n','惩罚；严厉对待，虐待',3,'gaokao'),
('puzzled','adj','困惑的；茫然的；搞糊涂的',3,'gaokao'),
('pyramid','n/v','金字塔；角锥体 v. 渐增；上涨；成金字塔状',3,'gaokao'),
('quake','v/n','震动；颤抖 n. 地震；颤抖',3,'gaokao'),
('quilt','n/v','被子；棉被 v. 东拼西凑地编；加软衬料后缝制',3,'gaokao'),
('radium','n','[化学] 镭（88号元素符号Ra）',3,'gaokao'),
('raincoat','n','（美）雨衣',3,'gaokao'),
('rainfall','n','降雨；降雨量',3,'gaokao'),
('razor','v/n','剃，用剃刀刮 n. 剃刀',3,'gaokao'),
('recognise','v','认出；承认，认可；识别',3,'gaokao'),
('redirect','v/adj/n','使改方向；重新寄送 adj. 再直接的 n. 再直接询问',3,'gaokao'),
('refreshments','n','点心；[食品] 茶点；小吃',3,'gaokao'),
('regards','n/v','致意，问候 v. 视为，注意（regard的第三人称单数）',3,'gaokao'),
('repairs','n/v','修理；[会计] 修理费；备件；修理工作（repair的复数形式） v. 修理；恢复（repair的三单形式）；弥补；纠正',3,'gaokao'),
('research','n/v','研究；调查 v. 研究；调查',3,'gaokao'),
('rest','v/n','使休息，使轻松；把…寄托于 n. 休息，静止；休息时间；剩余部分；支架',3,'gaokao'),
('restaurant','n','餐馆；[经] 饭店',3,'gaokao'),
('retell','v','复述；再讲；重述',3,'gaokao'),
('return','v/n/adj','返回；报答 n. 返回；归还；回球 adj. 报答的；回程的；返回的',3,'gaokao'),
('reuse','n/v','重新使用，再用 v. 再使用',3,'gaokao'),
('reviewer','n','评论者，评论家',3,'gaokao'),
('revision','n','[印刷] 修正；复习；修订本',3,'gaokao'),
('rewind','n/v','重绕；倒带器 v. 倒回；重绕',3,'gaokao'),
('rewrite','v/n','改写；重写 n. 重写或改写的文稿；改写的作品',3,'gaokao'),
('rhyme','n/v','韵律；韵脚；韵文；押韵词 v. 使押韵；用韵诗表达；把…写作诗',3,'gaokao'),
('rice','n/v','稻；米饭 v. 把…捣成米糊状',3,'gaokao'),
('rich','adj/n','富有的；肥沃的；昂贵的 n. (Rich)人名；(丹)里克；(捷)里赫；(英、西)里奇；(葡、法)里什',3,'gaokao'),
('riddle','v/n','解谜；给出谜；充满于 n. 谜语；粗筛；谜一般的人、东西、事情等',3,'gaokao'),
('ride','v/n','骑马；乘车；依靠；漂浮 n. 骑；乘坐；交通工具；可供骑行的路；（乘坐汽车等的）旅行；乘骑；（乘车或骑车的）短途旅程；供乘骑的游乐设施',3,'gaokao'),
('right','adj/v/n/adv','正确的；直接的；右方的 v. 复正；恢复平稳 n. 正确；右边；正义 adv. 正确地；恰当地；彻底地',3,'gaokao'),
('ripen','v','使成熟',3,'gaokao'),
('rise','v/n','上升；增强；起立；高耸 n. 上升；高地；增加；出现',3,'gaokao'),
('river','n','河，江',3,'gaokao'),
('road','n/vt/adj','公路，马路；道路；手段 vt. （狗）沿臭迹追逐（猎物） adj. （美）巡回的',3,'gaokao'),
('rock','n/v','岩石；摇滚乐；暗礁 v. 摇动；使摇晃',3,'gaokao'),
('role','n','角色；任务',3,'gaokao'),
('roof','n/v','屋顶；最高处，顶部；最高限度 v. 给…盖屋顶，覆盖',3,'gaokao'),
('room','n/v','房间；空间；余地；机会；房间里所有的人 v. 为…提供住处；租房，合住；投宿，住宿；留…住宿',3,'gaokao'),
('root','n/v','根；根源；词根；祖先 v. 生根；根除',3,'gaokao'),
('rose','n/adj/vt/vi','玫瑰；粉红色；蔷薇（花）；粉红色的葡萄酒 adj. 玫瑰花的；玫瑰色的；粉红色的；带有玫瑰香味的 vt. 使成玫瑰色，使（面颊）发红；使有玫瑰香味 vi. 起义( rise的过去式)；升起；（数量）增加；休会',3,'gaokao'),
('round','n/adj/adv/v','圆；循环；一回合；圆形物 adj. 圆的；完全的；大概的；肥胖的 adv. 在周围；迂回地；朝反方向；挨个 v. 完成；围捕；绕行；弄圆 prep. 附近；绕过；大约；在…周围',3,'gaokao'),
('rubber','n/adj/v','橡胶；橡皮；合成橡胶；按摩师 adj. 橡胶制成的 v. 涂橡胶于；用橡胶制造',3,'gaokao'),
('rubbish','n/adj','垃圾，废物；废话 adj. 毫无价值的',3,'gaokao'),
('rugby','n','英式橄榄球；拉格比（英格兰中部的城市）',3,'gaokao'),
('ruler','n','尺；统治者；[测] 划线板，划线的人',3,'gaokao'),
('run','v/n','经营；奔跑；运转 n. 奔跑；赛跑；趋向；奔跑的路程',3,'gaokao'),
('runner','n','跑步者；走私者；推销员；送信人',3,'gaokao'),
('running','n/adj/v','运转；赛跑；流出 adj. 连续的；流动的；跑着的；运转着的 v. 跑；运转（run的ing形式）；行驶',3,'gaokao'),
('russia','n','俄罗斯',3,'gaokao'),
('russian','adj/n','俄国的；俄语的 n. 俄语；俄国人',3,'gaokao'),
('sad','adj','难过的；悲哀的，令人悲痛的；凄惨的，阴郁的（形容颜色）',3,'gaokao'),
('sadness','n','悲哀',3,'gaokao'),
('safe','adj/n','安全的；可靠的；平安的 n. 保险箱；冷藏室；纱橱',3,'gaokao'),
('safety','n','安全；保险；安全设备；保险装置；安打',3,'gaokao'),
('sailing','n/adj/v','航行，航海；启航；航海术 adj. 航行的 v. 航行，起航（sail的现在分词形式）',3,'gaokao'),
('sale','n','销售；出售；拍卖；销售额；廉价出售',3,'gaokao'),
('salesgirl','n','女售货员，女店员',3,'gaokao'),
('saleswoman','n','[贸易] 女售货员；[贸易] 女店员',3,'gaokao'),
('salt','n/adj/v','盐；风趣，刺激性 adj. 咸水的；含盐的，咸味的；盐腌的；猥亵的 v. 用盐腌；给…加盐；将盐撒在道路上使冰或雪融化',3,'gaokao'),
('salty','adj','咸的；含盐的',3,'gaokao'),
('same','adj/pron/adv/n','相同的；同一的；上述的（通常与the连用）；无变化的 pron. 同样的事物或人（通常与the连用） adv. 同样地（通常与the连用） n. (Same)人名；(意)萨梅',3,'gaokao'),
('sand','n/v','沙；沙地；沙洲；沙滩；沙子 v. 撒沙于；以沙掩盖；用砂纸等擦平或磨光某物；使撒沙似地布满；给…掺沙子',3,'gaokao'),
('satisfy','v','满足， 使满意',3,'gaokao'),
('saturday','n','星期六',3,'gaokao'),
('saying','n/v','话；谚语；言论 v. 说（say的ing形式）',3,'gaokao'),
('scarf','n/v','围巾；嵌接，嵌接处；头巾领巾 v. 披嵌接；用围巾围',3,'gaokao'),
('scene','n','场面；情景；景象；事件',3,'gaokao'),
('sceptical','adj','怀疑的；怀疑论的；习惯怀疑的',3,'gaokao'),
('school','n/v','学校；学院；学派；鱼群 v. 教育',3,'gaokao'),
('schoolbag','n','书包',3,'gaokao'),
('schoolmate','n','同学；同窗',3,'gaokao'),
('science','n','科学；技术；学科；理科',3,'gaokao'),
('scientist','n','科学家',3,'gaokao'),
('scores','n/v','考试成绩；比分（score的复数） v. 得分（score的第三人称单数形式）；刻划',3,'gaokao'),
('scotland','n','苏格兰',3,'gaokao'),
('scottish','adj/n','苏格兰的；苏格兰人的；苏格兰语的 n. 苏格兰人；苏格兰语',3,'gaokao'),
('sea','n','海；海洋；许多；大量',3,'gaokao'),
('seagull','n','海鸥',3,'gaokao'),
('seaman','n','海员，水手；水兵',3,'gaokao'),
('search','v/n','搜寻；调查；探求 n. 搜寻；探究，查究',3,'gaokao'),
('seashell','n','海贝，贝壳；海贝壳',3,'gaokao'),
('season','n/v','时期；季节；赛季 v. 给…调味；使适应',3,'gaokao'),
('seat','n/v','座位；所在地；职位 v. 使…坐下；可容纳…的；使就职',3,'gaokao'),
('seaweed','n','海藻，海草',3,'gaokao'),
('secondhand','adj/adv','二手的；旧的；间接获得的；做旧货生意的 adv. 间接地；间接听来；以旧货',3,'gaokao'),
('secret','n/adj','秘密；秘诀；机密 adj. 秘密的；机密的',3,'gaokao'),
('see','v/n','看见；理解；领会 n. (See)人名；(英)西伊；(柬)塞；(德)泽',3,'gaokao'),
('seem','v/n','似乎；像是；装作 n. (Seem)人名；(英)西姆',3,'gaokao'),
('self','n/adj/vt/vi','自己，自我；本质；私心 adj. 同一的 vt. 使自花授精；使近亲繁殖 vi. 自花授精',3,'gaokao'),
('sell','v/n','销售；推销；出卖；欺骗 n. 销售；失望；推销术',3,'gaokao'),
('semicircle','n','半圆，半圆形',3,'gaokao'),
('send','v/n','发送，寄；派遣；使进入；发射 n. 上升运动',3,'gaokao'),
('sense','n/v','感觉，功能；观念；道理；理智 v. 感觉到；检测',3,'gaokao'),
('separation','n','分离，分开；间隔，距离；[法] 分居；缺口',3,'gaokao'),
('september','n','九月',3,'gaokao'),
('serious','adj','严肃的，严重的；认真的；庄重的；危急的',3,'gaokao'),
('servant','n','仆人，佣人；公务员；雇工',3,'gaokao'),
('service','n/adj/v','服务，服侍；服役；仪式 adj. 服务性的；耐用的；服现役的 v. 维修，检修；保养',3,'gaokao'),
('settler','n','移居者；殖民者',3,'gaokao'),
('seven','num/n/adj','七个，七 n. 七个，七 adj. 七的；七个的',3,'gaokao'),
('seventeen','n/adj/num','十七，十七个 adj. 十七岁的；十七的，十七个的 num. 十七',3,'gaokao'),
('seventh','n/adj/adv','第七；七分之一 adj. 第七的；七分之一的 adv. 居第七位地',3,'gaokao'),
('seventy','n/adj/num','七十；七十个；七十岁；七十年代 adj. 七十的；七十个的；七十岁的 num. 七十',3,'gaokao'),
('several','adj/pron','几个的；各自的 pron. 几个；数个',3,'gaokao'),
('sex','n/v','性；性别；性行为；色情 v. 引起…的性欲；区别…的性别',3,'gaokao'),
('shadow','n/v/adj','阴影；影子；幽灵；庇护；隐蔽处 v. 遮蔽；使朦胧；尾随；预示 adj. 影子内阁的',3,'gaokao'),
('shake','v/n','动摇；摇动；震动；握手 n. 摇动；哆嗦',3,'gaokao'),
('shall','aux','应；会；将；必须',3,'gaokao'),
('shanghai','n','上海（中国东部港市）',3,'gaokao'),
('shape','n/v','形状；模型；身材；具体化 v. 形成；塑造，使成形；使符合',3,'gaokao'),
('share','v/n','分享，分担；分配 n. 份额；股份',3,'gaokao'),
('sharp','adj/adv/n/vt','急剧的；锋利的；强烈的；敏捷的；刺耳的 adv. 急剧地；锐利地；突然地 n. 尖头；骗子；内行 vt. 磨快；把音调升高 vi. 打扮；升音演奏',3,'gaokao'),
('sharpen','v','削尖；磨快；使敏捷；加重',3,'gaokao'),
('sharpener','n','卷笔刀；[机] 磨具；研磨者',3,'gaokao'),
('shaver','n','理发师；电动剃刀',3,'gaokao'),
('sheep','n','羊，绵羊；胆小鬼',3,'gaokao'),
('shine','v/n','发出光；反射光，闪耀；出类拔萃，表现突出；露出；照耀；显露；出众 n. 光亮，光泽；好天气；擦亮；晴天；擦皮鞋；鬼把戏或诡计',3,'gaokao'),
('ship','v/n','运送，乘船；以船运送 n. 船；舰；太空船',3,'gaokao'),
('shirt','n','衬衫；汗衫，内衣',3,'gaokao'),
('shoe','n/v','鞋；蹄铁；外胎 v. 给……穿上鞋；穿……鞋',3,'gaokao'),
('shooting','n/v','射击；打猎；摄影；射门 v. 射击（shoot的ing形式）',3,'gaokao'),
('shop','n/v','商店；店铺 v. 购物',3,'gaokao'),
('shopkeeper','n','店主，老板',3,'gaokao'),
('shopping','n/v','购物，买东西 v. 购物（shop的ing形式）',3,'gaokao'),
('short','adj/n/adv','短的；不足的；矮的，低的 n. 短；缺乏；短路；短裤 adv. 不足；突然；唐突地',3,'gaokao'),
('shorts','n','短裤',3,'gaokao'),
('shout','v/n','呼喊；喊叫；大声说 n. 呼喊；呼叫',3,'gaokao'),
('show','v/n','显示；说明；演出；展出 n. 显示；表演；炫耀',3,'gaokao'),
('shut','v/n/adj','关闭；停业；幽禁 n. 关闭 adj. 关闭的；围绕的',3,'gaokao'),
('shy','adj/v/n','害羞的；畏缩的，胆怯的 v. 投；畏缩；惊退；厌恶 n. 投掷；惊跳',3,'gaokao'),
('sick','adj/n/v','厌恶的；病态的；不舒服；渴望的；恶心的 ；生病的 n. 病人 v. 使狗去咬；呕吐；追击',3,'gaokao'),
('sickness','n','疾病；呕吐；弊病',3,'gaokao'),
('side','n/v/adj','方面；侧面；旁边 v. 支持；赞助；偏袒 adj. 旁的，侧的',3,'gaokao'),
('sideway','n/adv/adj','人行道；小巷 adv. 斜地里 adj. 旁边的；向侧面的（等于sideways）',3,'gaokao'),
('sincerely','adv','真诚地；由衷地，诚恳地',3,'gaokao'),
('sing','v/n','唱歌；歌颂；鸣叫；呼号 n. 演唱；鸣声；呼啸声',3,'gaokao'),
('singer','n','歌手，歌唱家',3,'gaokao'),
('sir','n','先生；（用于姓名前）爵士；阁下；（中小学生对男教师的称呼）先生；老师',3,'gaokao'),
('sister','n/adj','姐妹；（称志同道合者）姐妹；修女；护士 adj. 姐妹般的；同类型的',3,'gaokao'),
('sit','v/n','坐；位于 n. (Sit)人名；(东南亚国家华语)硕；(罗)西特',3,'gaokao'),
('six','num/n','六，六个 n. 六，六个',3,'gaokao'),
('sixteen','adj/num','十六的，十六个的 num. 十六',3,'gaokao'),
('sixteenth','num/adj','第十六；十六分之一 adj. 第十六的；十六分之一的',3,'gaokao'),
('sixth','n/adj','月的第六日，（与the连用的）第六个；六分之一 adj. （与 the 连用）第六的，第六个的；六分之一的',3,'gaokao'),
('sixty','num','六十；六十个',3,'gaokao'),
('size','n/adj/v','大小；尺寸 adj. 一定尺寸的 v. 依大小排列',3,'gaokao'),
('skate','v/n','滑冰；滑过 n. 溜冰；冰鞋',3,'gaokao'),
('skateboard','n/v','溜冰板 v. 用滑板滑行',3,'gaokao'),
('ski','n/v/adj','滑雪橇 v. 滑雪 adj. 滑雪（用）的',3,'gaokao'),
('skill','n','技能，技巧；本领，技术',3,'gaokao'),
('skillfully','adv','巧妙地；精巧地',3,'gaokao'),
('skin','n/v','皮肤；外皮 v. 剥皮',3,'gaokao'),
('skirt','n/v','裙子 v. 绕过，回避；位于…边缘',3,'gaokao'),
('sky','n/v','天空；顶点 v. 把…投向空中；把…挂得过高',3,'gaokao'),
('sleep','v/n','睡，睡觉 n. 睡眠',3,'gaokao'),
('sleepy','adj','欲睡的；困乏的；不活跃的',3,'gaokao'),
('slow','adj/v/adv/n','慢的；减速的；迟钝的 v. 变慢；变萧条 adv. 慢慢地；迟缓地 n. (Slow)人名；(英)斯洛',3,'gaokao'),
('smell','v/n','嗅，闻；有…气味 n. 气味，嗅觉；臭味',3,'gaokao'),
('smelly','adj','有臭味的，发臭的',3,'gaokao'),
('smile','v/n','微笑 n. 微笑；笑容；喜色',3,'gaokao'),
('smog','n','烟雾',3,'gaokao'),
('smoke','n/v','烟；抽烟；无常的事物 v. 冒烟，吸烟；抽烟；弥漫',3,'gaokao'),
('smoker','n','吸烟者；薰制工',3,'gaokao'),
('smoking','n/adv/adj/v','抽烟；冒气 adv. 冒着烟 adj. 准许吸烟的 v. 吸烟；冒烟（smoke的现在分词）',3,'gaokao'),
('snake','n/v','蛇；阴险的人 v. 迂回前进',3,'gaokao'),
('sneaker','n','运动鞋；卑鄙者；鬼鬼祟祟做事的人',3,'gaokao'),
('snow','n/v','雪，积雪；下雪 v. 降雪',3,'gaokao'),
('snowball','n/v','雪球 v. 掷雪球；滚雪球般增大',3,'gaokao'),
('snowman','n','雪人',3,'gaokao'),
('snowy','adj','下雪的，多雪的；被雪覆盖的；洁白无瑕的',3,'gaokao'),
('soap','n/v','肥皂 v. 将肥皂涂在……上；对……拍马屁（俚语）',3,'gaokao'),
('sob','v/n','啜泣，呜咽；（风等）发出呜咽声 n. 啜泣，呜咽',3,'gaokao'),
('soccer','n','英式足球，足球',3,'gaokao'),
('society','n','社会；交往；社团；社交界',3,'gaokao'),
('sock','n/v/adv/adj','短袜；一击 v. 重击；给……穿袜 adv. 正着地；不偏不倚地 adj. 非常成功的',3,'gaokao'),
('socket','n/vt','插座；窝，穴；牙槽 vt. 给…配插座',3,'gaokao'),
('soft','adj/adv/n','软的，柔软的；温柔的，温和的；软弱的；笨的 adv. 柔软地；温和地 n. 柔性；柔软的东西；柔软部分',3,'gaokao'),
('softball','n','垒球；垒球运动',3,'gaokao'),
('soldier','n/v','军人；[昆] 兵蚁；懒汉；一片烤面包 v. 当兵；磨洋工；坚持干；假称害病',3,'gaokao'),
('some','adj/pron/adv','一些；某个；大约；相当多的 pron. 一些；若干；其中的一部分；（数量不确切时用）有些人 adv. 非常；相当；<美>稍微',3,'gaokao'),
('someone','pron','有人，某人',3,'gaokao'),
('something','pron/n/adv/adj','某事；某物 n. 重要的人；值得重视的事 adv. 非常；有点；大约 adj. 大约；有点象',3,'gaokao'),
('sometimes','adv','有时，间或',3,'gaokao'),
('somewhere','adv/n','在某处；到某处 n. 某个地方',3,'gaokao'),
('son','n','儿子；孩子（对年轻人的称呼）；男性后裔',3,'gaokao'),
('song','n','歌曲；歌唱；诗歌；鸣声',3,'gaokao'),
('soon','adv','快；不久，一会儿；立刻；宁愿',3,'gaokao'),
('sorry','adj','遗憾的；对不起的，抱歉的 int. 对不起，抱歉（表示委婉的拒绝等）',3,'gaokao'),
('soul','n/adj','灵魂；心灵；精神；鬼魂 adj. 美国黑人文化的',3,'gaokao'),
('soup','n/v','汤，羹；马力 v. 加速；增加马力',3,'gaokao'),
('south','n/adv/adj','南方，南边；南部 adv. 在南方，向南方 adj. 南的，南方的',3,'gaokao'),
('southern','adj/n','南的；南方的 n. 南方人',3,'gaokao'),
('southwest','n/adj/adv','西南方 adj. 西南的 adv. 往西南；来自西南',3,'gaokao'),
('souvenirs','n','纪念品；旅游纪念品；回忆',3,'gaokao'),
('space','n/v','空间；太空；距离 v. 留间隔',3,'gaokao'),
('spaceship','n','[航] 宇宙飞船',3,'gaokao'),
('spaghetti','n','意大利式细面条',3,'gaokao'),
('spain','n','西班牙',3,'gaokao'),
('spanish','adj/n','西班牙的；西班牙人的；西班牙语的 n. 西班牙语；西班牙人',3,'gaokao'),
('sparrow','n','麻雀；矮小的人',3,'gaokao'),
('speak','v','说话；演讲；表明；陈述',3,'gaokao'),
('speaker','n','演讲者；扬声器；说话者；说某种语言的人',3,'gaokao'),
('spear','n/v','矛，枪 v. 用矛刺',3,'gaokao'),
('special','n/adj','特使，特派人员；特刊；特色菜；专车；特价商品 adj. 特别的；专门的，专用的',3,'gaokao'),
('speech','n','演讲；讲话；[语] 语音；演说',3,'gaokao'),
('speed','v/n','超速，加速；加速，迅速前行；兴隆 n. 速度，速率；迅速，快速；昌盛，繁荣',3,'gaokao'),
('spell','v/n','拼，拼写；意味着；招致；拼成；迷住；轮值 n. 符咒；一段时间；魅力',3,'gaokao'),
('spend','v/n','度过，消磨（时光）；花费；浪费；用尽 n. 预算',3,'gaokao'),
('spirit','n/v','精神；心灵；情绪；志气；烈酒 v. 鼓励；鼓舞；诱拐',3,'gaokao'),
('spoken','adj/v','口语的，口头的 v. 说（speak的过去分词）',3,'gaokao'),
('spoon','n/v','匙，勺子；一杓的量 v. 用匙舀；使成匙状',3,'gaokao'),
('spoonful','n','一匙；一匙的量',3,'gaokao'),
('sport','n/v/adj','运动；游戏；娱乐；运动会；玩笑 v. 游戏 adj. 运动的',3,'gaokao'),
('squid','n','鱿鱼；乌贼；枪乌贼',3,'gaokao'),
('squirrel','n/v','松鼠；松鼠毛皮 v. 贮藏',3,'gaokao'),
('stamp','n/v','邮票；印记；标志；跺脚 v. 铭记；标出；盖章于…；贴邮票于…；用脚踩踏',3,'gaokao'),
('stand','v/n','站立；位于；停滞 n. 站立；立场；看台；停止',3,'gaokao'),
('standard','n/adj','标准；水准；旗；度量衡标准 adj. 标准的；合规格的；公认为优秀的',3,'gaokao'),
('starvation','n','饿死；挨饿；绝食',3,'gaokao'),
('state','n/v/adj','国家；州；情形 v. 规定；声明；陈述 adj. 国家的；州的；正式的',3,'gaokao'),
('station','n/v','车站；驻地；地位；身份 v. 配置；安置；驻扎',3,'gaokao'),
('stay','v/n','停留；坚持；暂住；停下 n. 逗留；停止；支柱',3,'gaokao'),
('step','n/v','步，脚步；步骤；步伐；梯级 v. 踏，踩；走',3,'gaokao'),
('steward','n/vi/vt','管家；乘务员；膳务员；工会管事 vi. 当服务员；当管事 vt. 管理',3,'gaokao'),
('stewardess','n','女管家；女干事；女服务员',3,'gaokao'),
('stick','v/n','刺，戳；伸出；粘贴 n. 棍；手杖；呆头呆脑的人',3,'gaokao'),
('still','adv/adj/n/conj','仍然；更；静止地 adj. 静止的，不动的；寂静的，平静的；不起泡的 n. 寂静；剧照；蒸馏室 conj. 仍然；但是；尽管如此 v. 蒸馏；使…静止；使…平静下来',3,'gaokao'),
('stomach','n/v','胃；腹部；胃口 v. 忍受；吃下',3,'gaokao'),
('stomachache','n','腹痛，肚子痛；胃痛',3,'gaokao');

INSERT IGNORE INTO `dict_word` (`word`,`pos`,`meaning`,`difficulty`,`level`) VALUES
('stop','v/n','停止；堵塞；断绝 n. 停止；车站；障碍；逗留',3,'gaokao'),
('stopwatch','n/vt','码表；跑表 vt. 用秒表测定时间',3,'gaokao'),
('story','n/vt/vi','故事；小说；新闻报道；来历；假话 vt. 用历史故事画装饰 vi. 说谎',3,'gaokao'),
('straight','adj/adv/n','直的；连续的；笔直的；正直的；整齐的；异性恋的 adv. 直接地；不断地；立即；坦率地 n. 直；直线；直男，直女，异性恋者',3,'gaokao'),
('strawberry','n','草莓；草莓色',3,'gaokao'),
('street','n/adj','街道 adj. 街道的',3,'gaokao'),
('strong','adj/adv/n','坚强的；强壮的；牢固的；擅长的 adv. 强劲地；猛烈地 n. (Strong)人名；(英)斯特朗',3,'gaokao'),
('student','n','学生；学者',3,'gaokao'),
('study','n/v','学习，研究；课题；书房；学问 v. 学习；考虑；攻读；细察',3,'gaokao'),
('stupid','adj/n','愚蠢的；麻木的；乏味的 n. 傻瓜，笨蛋',3,'gaokao'),
('style','n/v','风格；时尚；类型；字体 v. 设计；称呼；使合潮流',3,'gaokao'),
('subtraction','n','[数] 减法；减少；差集',3,'gaokao'),
('succeed','v','成功；继承；继任；兴旺',3,'gaokao'),
('success','n','成功，成就；胜利；大获成功的人或事物',3,'gaokao'),
('successful','adj','成功的；一帆风顺的',3,'gaokao'),
('such','adj/n','这样的，如此的 n. (Such)人名；(英)萨奇；(德)祖赫',3,'gaokao'),
('sudden','adj/n','突然的，意外的；快速的 n. 突然发生的事',3,'gaokao'),
('suffering','n/adj/v','受难；苦楚 adj. 受苦的；患病的 v. 受苦；蒙受（suffer的ing形式）',3,'gaokao'),
('sugar','n/v','糖；食糖；甜言蜜语 v. 加糖于；粉饰',3,'gaokao'),
('suggest','v','提议，建议；启发；使人想起；显示；暗示',3,'gaokao'),
('suitable','adj','适当的；相配的',3,'gaokao'),
('sun','n/v','太阳 v. 使晒',3,'gaokao'),
('sunburnt','adj/v','晒黑的；有晒斑的；日炙的 v. 晒黑（sunburn的过去式和过去分词）',3,'gaokao'),
('sunday','n','星期日；礼拜日',3,'gaokao'),
('sunglasses','n','太阳镜；凸透镜（sunglass的复数）',3,'gaokao'),
('sunny','adj','阳光充足的，和煦的；快活的；性情开朗的',3,'gaokao'),
('super','adj/n','特级的；极好的 n. 特级品，特大号；临时雇员',3,'gaokao'),
('superman','n','超人，能力非凡的',3,'gaokao'),
('supermarket','n','超级市场；自助售货商店',3,'gaokao'),
('supper','n','晚餐，晚饭；夜宵',3,'gaokao'),
('sure','adj/adv/n','确信的；可靠的；必定的 adv. 当然；的确 n. (Sure)人名；(英)休尔',3,'gaokao'),
('surface','n/adj/v','表面；表层；外观 adj. 表面的，肤浅的 v. 浮出水面',3,'gaokao'),
('surprise','n/v/adj','惊奇，诧异；突然袭击 v. 使惊奇；奇袭 adj. 令人惊讶的',3,'gaokao'),
('sweat','v/n','使出汗；流出；使干苦活；剥削；藉出汗减轻；焦急地期待 n. 汗；水珠；焦急；苦差使',3,'gaokao'),
('sweet','adj/n','甜的；悦耳的；芳香的；亲切的 n. 糖果；乐趣；芳香；宝贝',3,'gaokao'),
('swim','v/n/adj','游泳；漂浮；浸；眩晕 n. 游泳；漂浮；眩晕 adj. 游泳时穿戴的',3,'gaokao'),
('swimming','n/adj/v','游泳；目眩 adj. 游泳的；游泳用的；善于游泳的；晕眩的 v. 游泳；漂浮；旋转（swim的ing形式）',3,'gaokao'),
('swiss','adj/n','瑞士的；瑞士人的；瑞士风格的 n. 瑞士人；瑞士腔调',3,'gaokao'),
('switzerland','n','瑞士（欧洲国家）',3,'gaokao'),
('table','n/v/adj','桌子；表格；平地层 v. 制表；搁置；嵌合 adj. 桌子的',3,'gaokao'),
('tablet','n/vt','碑；药片；写字板；小块；平板电脑 vt. 用碑牌纪念；将(备忘录等)写在板上；将…制成小片或小块',3,'gaokao'),
('tail','n/v/adj','尾巴；踪迹；辫子；燕尾服 v. 尾随；装上尾巴 adj. 从后面而来的；尾部的',3,'gaokao'),
('take','v/n','拿，取；采取；接受（礼物等）；买，花费；耗费（时间等） n. 捕获量；看法；利益，盈益；（入场券的）售得金额',3,'gaokao'),
('tall','adj/adv/n','高的；长的；过分的；夸大的 adv. 夸大地 n. (Tall)人名；(马里、阿拉伯)塔勒；(芬、罗、瑞典)塔尔；(英)托尔；(土)塔勒',3,'gaokao'),
('tasty','adj/n','美味的；高雅的；有趣的 n. 可口的东西；引人入胜的东西',3,'gaokao'),
('taxi','v/n','乘出租车；滑行 n. 出租汽车',3,'gaokao'),
('taxpayer','n','纳税人',3,'gaokao'),
('tea','n/vt/vi','茶叶；茶树；茶点 vt. 给…沏茶 vi. 喝茶；进茶点',3,'gaokao'),
('teach','v/n','教；教授；教导 n. (Teach)人名；(英)蒂奇',3,'gaokao'),
('teacher','n','教师；导师',3,'gaokao'),
('teamwork','n','团队合作；协力',3,'gaokao'),
('teapot','n','茶壶',3,'gaokao'),
('tear','v/n','扯破， 撕开 n. 眼泪',3,'gaokao'),
('telegraph','n/v','[通信] 电报机，电报 v. 电汇；流露出；打电报给…',3,'gaokao'),
('telephone','n/v','（美）电话；电话机；电话耳机 v. 打电话',3,'gaokao'),
('television','n','电视，电视机；电视业',3,'gaokao'),
('tell','v/n','告诉，说；辨别；吩咐；断定 n. (Tell)人名；(英、德、瑞典)特尔；(罗、意)泰尔；(阿拉伯)塔勒',3,'gaokao'),
('temperature','n','温度；体温；气温；发烧',3,'gaokao'),
('ten','num/n','十个，十 n. (Ten)人名；(英)坦恩；(意)泰恩；(柬)登',3,'gaokao'),
('term','n/v','术语；学期；期限；条款；(代数式等的)项 v. 把…叫做',3,'gaokao'),
('test','n/v','试验；检验 v. 试验；测试',3,'gaokao'),
('text','n/v','[计] 文本；课文；主题 v. 发短信',3,'gaokao'),
('textbook','n','教科书，课本',3,'gaokao'),
('than','conj/prep/n','比（用于形容词、副词的比较级之后）；除…外（用于other等之后）；与其…（用于 rather等之后）；一…就（用于 no sooner等之后） prep. 比；超过 n. (Than)人名；(老、柬、德)坦；(缅)丹',3,'gaokao'),
('thank','v/n','感谢 n. 感谢 int. 谢谢',3,'gaokao'),
('thankful','adj','感谢的；欣慰的',3,'gaokao'),
('theirs','pron','他们的；她们的；它们的',3,'gaokao'),
('themselves','pron','他们自己；他们亲自',3,'gaokao'),
('then','adv/n/conj','然后；那么；于是；当时；此外 n. 那时 conj. 然后，当时',3,'gaokao'),
('there','adv/n','在那里；在那边；在那点上 int. 你瞧 n. 那个地方',3,'gaokao'),
('thermos','n','热水瓶',3,'gaokao'),
('thief','n','小偷，贼',3,'gaokao'),
('thin','adj/v/adv/n','薄的；瘦的；稀薄的；微弱的 v. 使瘦；使淡；使稀疏 adv. 稀疏地；微弱地 n. 细小部分',3,'gaokao'),
('thing','n','事情；东西；事物；情况',3,'gaokao'),
('think','v/n/adj','想；认为；想起；想像；打算 n. 想；想法 adj. 思想的',3,'gaokao'),
('third','num/adj','第三；三分之一 adj. 第三的；三分之一的',3,'gaokao'),
('thirst','n/v','渴望；口渴；热望 v. 渴望；口渴',3,'gaokao'),
('thirteen','n/num/adj','十三；十三岁；十三个 num. 十三 adj. 十三的；十三个的',3,'gaokao'),
('thirty','n/num/adj','三十年代 num. 三十 adj. 三十个的',3,'gaokao'),
('though','adv/conj/prep','可是，虽然；不过；然而 conj. 虽然；尽管 prep. 但',3,'gaokao'),
('thought','n/v','思想；思考；想法；关心 v. 想，思考；认为（think的过去式和过去分词）',3,'gaokao'),
('thousand','n/adj','一千；一千个；许许多多 adj. 成千的；无数的',3,'gaokao'),
('three','n/num/adj','三，三个 num. 三 adj. 三的，三个的',3,'gaokao'),
('thriller','n','惊险小说；使人毛骨悚然的东西；使人毛骨悚然的小说',3,'gaokao'),
('throw','v/n','投；抛；掷 n. 投掷；冒险',3,'gaokao'),
('thunderstorm','n','[气象] 雷暴；雷暴雨；大雷雨',3,'gaokao'),
('thursday','n','星期四',3,'gaokao'),
('tibet','n','西藏（中国一自治区）',3,'gaokao'),
('tibetan','adj/n','西藏的；藏族的 n. 藏语；西藏人',3,'gaokao'),
('tie','v/n','系；约束；打结；与…成平局 n. 领带；平局；鞋带；领结；不分胜负',3,'gaokao'),
('tiger','n','老虎；凶暴的人',3,'gaokao'),
('tight','adj/adv/n','紧的；密封的；绷紧的；麻烦的；严厉的；没空的；吝啬的 adv. 紧紧地；彻底地 n. (Tight)人名；(英)泰特',3,'gaokao'),
('till','n/prep/conj/v','[地理][水文] 冰碛；放钱的抽屉；备用现金 prep. 直到 conj. 直到为止 v. 耕种；犁',3,'gaokao'),
('timetable','n','时间表；时刻表；课程表',3,'gaokao'),
('tired','adj/v','疲倦的；厌倦的，厌烦的 v. 疲倦；对…腻烦（tire的过去分词形式）',3,'gaokao'),
('tobacco','n','烟草，烟叶；烟草制品；抽烟',3,'gaokao'),
('today','adv/n','今天；现今 n. 今天；现今',3,'gaokao'),
('together','adv/adj','一起；同时；相互；连续地；总共 adj. 新潮的；情绪稳定的，做事有效率的',3,'gaokao'),
('tokyo','n','东京（日本首都）',3,'gaokao'),
('tomato','n','番茄，西红柿',3,'gaokao'),
('tomb','n/vt','坟墓；死亡 vt. 埋葬',3,'gaokao'),
('tomorrow','n/adv','明天；未来 adv. 明天；未来地（等于to-morrow）',3,'gaokao'),
('ton','n','吨；很多，大量',3,'gaokao'),
('tongue','n/v','舌头；语言 v. 舔；斥责；用舌吹',3,'gaokao'),
('tonight','adv/n','在今晚 n. 今晚',3,'gaokao'),
('tool','n/v','工具，用具；器械，机床；手段 v. 使用工具；用机床装备工厂',3,'gaokao'),
('tooth','n/vt/vi','牙齿 vt. 给……装齿 vi. 啮合',3,'gaokao'),
('toothbrush','n','牙刷',3,'gaokao'),
('toothpaste','n','牙膏',3,'gaokao'),
('top','n/v/adj','顶部，顶端；上部；首席；陀螺 v. 高出，超越；结束；达到顶点 adj. 最高的，顶上的；头等的',3,'gaokao'),
('tortoise','n','龟，[脊椎] 乌龟（等于testudo）；迟缓的人',3,'gaokao'),
('totally','adv','完全地',3,'gaokao'),
('tourism','n','旅游业；游览',3,'gaokao'),
('tournament','n','锦标赛，联赛；比赛',3,'gaokao'),
('toward','prep/adj/n','向；对于；为了；接近 adj. 即将来到的，进行中的 n. (Toward)人名；(英)特沃德',3,'gaokao'),
('town','n','城镇，市镇；市内商业区',3,'gaokao'),
('toy','n/v/adj','玩具；小装饰品；不值钱的东西 v. 玩弄；调情；随随便便地对待 adj. 作为玩具的；玩物似的',3,'gaokao'),
('traditional','adj','传统的；惯例的',3,'gaokao'),
('train','n/v','火车；行列；长队；裙裾 v. 培养；训练；瞄准',3,'gaokao'),
('trainer','n','助理教练；训练员；驯马师；飞行练习器；运动鞋',3,'gaokao'),
('training','n/v','训练；培养；瞄准；整枝 v. 训练；教养（train的ing形式）',3,'gaokao'),
('tram','n/v','电车轨道；煤车 v. 用煤车运载',3,'gaokao'),
('translate','v','翻译；转化；解释；转变为；调动',3,'gaokao'),
('translator','n','译者；翻译器',3,'gaokao'),
('travel','vi','n&vi. 旅行',3,'gaokao'),
('traveler','n','旅行者；旅客；旅行推销员（等于traveller）',3,'gaokao'),
('tree','n/v','树；木料；树状物 v. 把赶上树',3,'gaokao'),
('trip','v/n','绊倒；远足；犯错误；轻快地走 n. 旅行；绊倒；差错',3,'gaokao'),
('trolleybus','n','无轨电车',3,'gaokao'),
('trouble','n/v','麻烦；烦恼；故障；动乱 v. 麻烦；使烦恼；折磨',3,'gaokao'),
('trousers','n','裤子，长裤',3,'gaokao'),
('truck','n/v/adj','卡车；交易；手推车 v. 驾驶卡车；以物易物 adj. （美）运货汽车的',3,'gaokao'),
('true','adj/adv/n/v','真实的；正确的 adv. 真实地；准确地 n. 真实；准确 v. 装准',3,'gaokao'),
('try','v/n','试图，努力；试验；审判；考验 n. 尝试；努力；试验',3,'gaokao'),
('tuesday','n','星期二',3,'gaokao'),
('turkey','n','火鸡；笨蛋；失败之作',3,'gaokao'),
('turn','v/n','转动，使旋转；转弯；翻过来；兑换 n. 转弯；变化；(损害或有益于别人的)行为，举动，举止',3,'gaokao'),
('turning','n/v','转向；旋转；回转；转弯处 v. 旋转（turn的ing形式）',3,'gaokao'),
('tv','abbr','电视（television）',3,'gaokao'),
('twelfth','adj/n','第十二的，第十二个的；十二分之一的 n. 第十二；月的第十二日',3,'gaokao'),
('twelve','n/num/adj','十二；十二个 num. 十二；十二个 adj. 十二的；十二个的',3,'gaokao'),
('twentieth','n/adj/num','二十分之一 adj. 第二十的；二十分之一的 num. 第二十',3,'gaokao'),
('twenty','n/num/adj','二十；二十年代 num. 二十 adj. 二十的',3,'gaokao'),
('twice','adv','两次；两倍',3,'gaokao'),
('two','n/adj/num','两个 adj. 两个的 num. 二',3,'gaokao'),
('typhoon','n','[气象] 台风',3,'gaokao'),
('uk','abbr/n','联合王国（United Kingdom） n. 英国',3,'gaokao'),
('un','abbr','联合国（United Nations）；硝酸铀铣（Uranyl Nitrate）',3,'gaokao'),
('unable','adj','不会的，不能的；[劳经] 无能力的；不能胜任的',3,'gaokao'),
('unbelievable','adj','难以置信的',3,'gaokao'),
('uncle','n','叔叔；伯父；伯伯；舅父；姨丈；姑父',3,'gaokao'),
('uncomfortable','adj','不舒服的；不安的',3,'gaokao'),
('unconditional','adj','无条件的；绝对的；无限制的',3,'gaokao'),
('understand','v','理解；懂；获悉；推断；省略',3,'gaokao'),
('undivided','adj/v','专心的；专一的；未分开的；完整的 v. 未分开（undivide的过去式和过去分词）',3,'gaokao'),
('unfair','adj','不公平的，不公正的',3,'gaokao'),
('unfortunate','adj','不幸的；令人遗憾的；不成功的',3,'gaokao'),
('unhappy','adj','不快乐的；不幸福的；不适当的',3,'gaokao'),
('unhealthy','adj','不健康的；危险的；有害身心健康的',3,'gaokao'),
('unimportant','adj','不重要的；琐碎的',3,'gaokao'),
('university','n','大学；综合性大学；大学校舍',3,'gaokao'),
('unmarried','adj/v','[法] 未婚的；单身的；独身的 v. 离婚（unmarry的过去分词）',3,'gaokao'),
('unpleasant','adj','讨厌的；使人不愉快的',3,'gaokao'),
('unsafe','adj','不安全的；危险的；不安稳的',3,'gaokao'),
('unsuccessful','adj','不成功的；失败的',3,'gaokao'),
('untrue','adj','不真实的；不合标准的；不忠实的；不正当的',3,'gaokao'),
('up','adv/prep/adj/n','起来；上涨；向上 prep. 在…之上；向…的较高处 adj. 涨的；起床的；向上的 n. 上升；繁荣',3,'gaokao'),
('upon','prep','在…上面',3,'gaokao'),
('upstairs','adv/adj/n','在楼上，向楼上；上楼；往楼上 adj. 楼上的 n. 楼上',3,'gaokao'),
('upwards','adv','向上， 往上',3,'gaokao'),
('use','n/v','使用；用途；发挥 v. 利用；耗费',3,'gaokao'),
('used','adj/v','习惯的；二手的，使用过的 v. 用（use的过去式）；（used to）过去常做',3,'gaokao'),
('useful','adj','有用的，有益的；有帮助的',3,'gaokao'),
('useless','adj','无用的；无效的',3,'gaokao'),
('user','n','用户',3,'gaokao'),
('usual','adj','通常的，惯例的；平常的',3,'gaokao'),
('usually','adv','通常，经常',3,'gaokao'),
('valley','n','山谷；流域；溪谷',3,'gaokao'),
('vanilla','n/adj','香子兰，香草 adj. 香草味的',3,'gaokao'),
('vase','n','瓶；花瓶',3,'gaokao'),
('veal','n','小牛（等于vealer）；小牛肉',3,'gaokao'),
('vegetable','n/adj','蔬菜；植物；植物人 adj. 蔬菜的；植物的',3,'gaokao'),
('vest','n/v','背心；汗衫 v. 授予；使穿衣',3,'gaokao'),
('victory','n','胜利；成功；克服',3,'gaokao'),
('videophone','n','电视电话',3,'gaokao'),
('viewer','n','观察者；观看者；观众；[仪] 指示器',3,'gaokao'),
('village','n','村庄；村民；（动物的）群落',3,'gaokao'),
('villager','n','乡村居民，村民',3,'gaokao'),
('violinist','n','小提琴演奏者，小提琴家',3,'gaokao'),
('visitor','n','访问者，参观者；视察者；候鸟',3,'gaokao'),
('voice','n/v','声音；嗓音；发言权；愿望 v. 表达；吐露',3,'gaokao'),
('volleyball','n','排球',3,'gaokao'),
('wait','v/n','等候；推迟；延缓 n. 等待；等候',3,'gaokao'),
('waiter','n','服务员，侍者',3,'gaokao'),
('wake','v/n','醒来；唤醒；警觉 n. 尾迹；守夜；守丧',3,'gaokao'),
('walk','n/v','步行，走；散步 v. 散步；走过',3,'gaokao'),
('walkman','n','随身听（商标名称）',3,'gaokao'),
('wall','n/v/adj','墙壁，围墙；似墙之物 v. 用墙围住，围以墙 adj. 墙壁的',3,'gaokao'),
('war','n/v','战争，斗争；军事，战术；冲突，对抗，竞争 v. 打仗，作战；对抗',3,'gaokao'),
('warm','adj/v/n','温暖的；热情的 v. 同情；激动；变温暖 n. 取暖；加热',3,'gaokao'),
('warn','vt','警告； 预告',3,'gaokao'),
('wash','n/v','洗涤；洗的衣服；化妆水；冲积物 v. 洗涤；洗刷；冲走；拍打',3,'gaokao'),
('washroom','n','洗手间；盥洗室；厕所',3,'gaokao'),
('waste','n/v/adj','浪费；废物；荒地；损耗；地面风化物 v. 浪费；消耗；使荒芜 adj. 废弃的；多余的；荒芜的',3,'gaokao'),
('watch','v/n','观察；注视；看守；警戒 n. 手表；监视；守护；值班人',3,'gaokao'),
('watermelon','n','西瓜',3,'gaokao'),
('wayside','n/adj','路旁 adj. 路旁的',3,'gaokao'),
('weak','adj','[经] 疲软的；虚弱的；无力的；不牢固的',3,'gaokao'),
('weather','n/v/adj','天气；气象；气候；处境 v. 经受住；使风化；侵蚀；使受风吹雨打 adj. 露天的；迎风的',3,'gaokao'),
('weatherman','n','气象员；天气预报员',3,'gaokao'),
('website','n','网站（全球资讯网的主机站）',3,'gaokao'),
('wednesday','n','星期三',3,'gaokao'),
('week','n','周，星期',3,'gaokao'),
('weekday','n','平日，普通日；工作日',3,'gaokao'),
('weekend','n/adj/v','周末，周末休假；周末聚会 adj. 周末的，周末用的 v. 度周末',3,'gaokao'),
('weigh','v/n','权衡；考虑；称…重量 n. 权衡；称重量',3,'gaokao'),
('weight','n/v','重量，重力；负担；砝码；重要性 v. 加重量于，使变重',3,'gaokao'),
('welcome','adj/n/v','受欢迎的 n. 欢迎 v. 欢迎 int. 欢迎',3,'gaokao'),
('well','adv/adj/n/v','很好地；充分地；满意地；适当地 adj. 良好的；健康的；适宜的 n. 井；源泉 v. 涌出',3,'gaokao'),
('west','n/adj/adv','西；西方；西部 adj. 西方的；朝西的 adv. 在西方；向西方；自西方',3,'gaokao'),
('western','adj/n','西方的，西部的；有西方特征的 n. 西方人；西部片，西部小说',3,'gaokao'),
('westerner','n','西方人，欧美人；美国西部的人',3,'gaokao'),
('westwards','adv/adj','向西 adj. 向西的',3,'gaokao'),
('wet','adj/n/v','[气象][物] 潮湿的；有雨的 n. 雨天；湿气 v. 弄湿',3,'gaokao'),
('whenever','conj/adv','每当；无论何时 adv. 不论何时；随便什么时候',3,'gaokao'),
('wherever','adv/conj','无论什么地方；究竟在哪里 conj. 无论在哪里；无论什么情况下',3,'gaokao'),
('whether','conj/pron','是否；不论 pron. 两个中的哪一个',3,'gaokao'),
('while','conj/n/v','虽然；然而；当……的时候 n. 一会儿；一段时间 v. 消磨；轻松地度过',3,'gaokao'),
('whole','adj/n','完整的；纯粹的 n. 整体；全部',3,'gaokao'),
('whom','pron','谁（who的宾格）',3,'gaokao'),
('whose','pron','谁的（疑问代词）',3,'gaokao'),
('why','adv','哎呀！什么？ adv. 为什么',3,'gaokao'),
('wide','adj/adv/n','广泛的；宽的，广阔的；张大的；远离目标的 adv. 广泛地；广阔地；充分地 n. 大千世界',3,'gaokao'),
('wife','n','妻子，已婚妇女；夫人',3,'gaokao'),
('wild','adj/n/adv','野生的；野蛮的；狂热的；荒凉的 n. 荒野 adv. 疯狂地；胡乱地',3,'gaokao'),
('willingly','adv','欣然地；愿意地，乐意地',3,'gaokao'),
('willingness','n','乐意；心甘情愿；自动自发',3,'gaokao'),
('win','v/n','赢得；在…中获胜；劝诱 n. 赢；胜利',3,'gaokao'),
('windbreaker','n','防风夹克，同windcheater',3,'gaokao'),
('window','n','窗；窗口；窗户',3,'gaokao'),
('wine','n/v','酒，葡萄酒；紫红色 v. 喝酒',3,'gaokao'),
('winner','n','胜利者',3,'gaokao'),
('winter','n/v/adj','冬季；年岁；萧条期 v. 过冬 adj. 冬天的；越冬的',3,'gaokao'),
('wipe','v/n','擦；消除；涂上 n. 擦拭；用力打',3,'gaokao'),
('wish','n/v','希望；祝福；心愿 v. 祝愿；渴望；向…致问候语',3,'gaokao'),
('within','prep/adv/n','在…之内 adv. 在内部 n. 里面',3,'gaokao'),
('without','prep/adv/n','没有；超过；在…外面 adv. 户外；在外面；没有或不显示某事物 n. 外部；外面',3,'gaokao'),
('woman','n','妇女；女性；成年女子',3,'gaokao'),
('wonderful','adj','极好的，精彩的，绝妙的；奇妙的；美妙；胜；神妙',3,'gaokao'),
('woo','v','追求；招致；向…求爱；恳求',3,'gaokao'),
('wood','n/vi/vt','木材；木制品；树林 vi. 收集木材 vt. 植林于；给…添加木柴',3,'gaokao'),
('woolen','adj','羊毛的， 羊毛制的',3,'gaokao'),
('woollen','adj/n','羊毛制的 n. 毛织品',3,'gaokao'),
('word','n/v','[语] 单词；话语；消息；诺言；命令 v. 用言辞表达',3,'gaokao'),
('workday','n/adj','工作日 adj. 日常的，工作日的；平凡的',3,'gaokao'),
('worker','n','工人；劳动者；职蚁',3,'gaokao'),
('workforce','n','劳动力；工人总数，职工总数',3,'gaokao'),
('workmate','n','同事；工友',3,'gaokao'),
('workplace','n','工作场所；车间',3,'gaokao'),
('works','n','作品；工厂；工程结构',3,'gaokao'),
('worn','adj/v/n','疲倦的；用旧的 v. 穿；磨损（wear的过去分词）；佩戴 n. (Worn)人名；(柬)翁；(英、葡)沃恩',3,'gaokao'),
('worried','adj','担心的',3,'gaokao'),
('worry','n/v','担心；烦恼；撕咬 v. 担心；发愁；折磨',3,'gaokao'),
('worse','adj/adv/n','更坏的；更差的；更恶劣的（bad的比较级）；（病情）更重的（ill的比较级） adv. 更糟；更坏；更恶劣地；更坏地 n. 更坏的事；更恶劣的事',3,'gaokao'),
('wounded','adj/n/v','受伤的 n. 受伤者，伤员 v. 使受伤（wound的过去分词）',3,'gaokao'),
('write','v','写，写字；写作，作曲；写信',3,'gaokao'),
('wrong','adv/n/adj/v','错误地；邪恶地，不正当地 n. 坏事；不公正 adj. 错误的；失常的；不适当的 v. 委屈；无理地对待；诽谤',3,'gaokao'),
('yellow','adj/n/v','黄色的；黄皮肤的 n. 黄色；黄种人；黄色颜料 v. 使变黄或发黄',3,'gaokao'),
('yes','adv/n','是, 是的 n. 是（表示肯定）',3,'gaokao'),
('yesterday','n/adv','昨天；往昔 adv. 昨天',3,'gaokao'),
('yet','adv/conj/n','还；但是；已经 conj. 但是；然而 n. (Yet)人名；(东南亚国家华语)一',3,'gaokao'),
('yoghurt','n','酸奶（等于yoghourt）；酸乳酪',3,'gaokao'),
('young','adj/n','年轻的；初期的；没有经验的 n. 年轻人；（动物的）崽，仔',3,'gaokao'),
('yours','pron/adj','你（们）的东西；你的责任[义务]；你的家属；来信，尊函 adj. 你（们）的（东西）；信末署名前用语',3,'gaokao'),
('yourself','pron','你自己',3,'gaokao'),
('yourselves','pron','你们自己；你们本人（yourself的复数）',3,'gaokao'),
('yummy','adj/n','好吃的；美味的；愉快的 n. 美味的东西；令人喜爱的东西',3,'gaokao'),
('zebra','n/adj','[脊椎] 斑马 adj. 有斑纹的',3,'gaokao'),
('zero','n/num','零点，零度 num. 零',3,'gaokao'),
('zip','n/v','拉链；活力，精力；尖啸声，撕裂声；一种程序压缩的档案文件格式 v. 拉开或拉上；以尖啸声行进',3,'gaokao'),
('zipper','n/v','拉链 v. 拉上拉链',3,'gaokao'),
('zoo','n','动物园',3,'gaokao'),
('zoom','n/v','急速上升；嗡嗡声；[摄] 变焦摄影 v. 急速上升；摄像机移动',3,'gaokao');

-- 校验
-- SELECT level, COUNT(*) FROM dict_word GROUP BY level;
